# Generated by Django 3.0.3 on 2020-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullgame', '0004_auto_20200225_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_category',
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2),
        ),
    ]
